### ISSUE TITLE
default layout should not display horizontal page scrollbar 

### ISSUE THREAD

**Issue by likui628** [developer-plus/vue-hbs-admin#110]
### Describe the bug

默认布局不应该出现横向滚动条
![image](https://user-images.githubusercontent.com/90845831/166638396-030e557f-b7a3-4576-bd34-b7c227776635.png)
<img width="270" alt="8ba18eff9f382d4597929edbcc645a0" src="https://user-images.githubusercontent.com/90845831/166650674-98504546-05dd-4d63-b29c-a90d1a8b6646.png">

<img width="489" alt="32579316ec1bf3a5ae59d21b6e1f15c" src="https://user-images.githubusercontent.com/90845831/166650639-2c85557c-1ff9-4355-ab1d-ca91e17167c8.png">

**Comment by xiaoxiayan** [comment]
认领一下
