### ISSUE TITLE
CI: 使用 renovatebot 为项目自动升级依赖

### ISSUE THREAD

**Issue by alexzhang1030** [developer-plus/vue-hbs-admin#27]
## 1. renovatebot 地址
[github repo](https://github.com/renovatebot/renovate)

## 2. 为什么使用
自动检测项目依赖的版本，并采用 PR 的方式来升级依赖

## 3. 为什么是 renovatebot 而不是 dependabot ?

renovatebot 可以一次 PR 升级多个依赖的版本，而 dependbot 只能是一次 pr 升级一个依赖的版本，显然不利于 commit-msg 的清爽

**Comment by alexzhang1030** [comment]
@Hongbusi

**Comment by alexzhang1030** [comment]
> 为什么要自动升级依赖，会有造成版本不符合问题啊，和 .lock 文件意义冲突了吧

及时更新依赖版本对于安全性非常重要，而且更新会自动更新 lock 文件

**Comment by Hongbusi** [comment]
如何去保证更新之后的依赖版本和其他的依赖之间不产生冲突，也会是个问题。

**Comment by alexzhang1030** [comment]
> 比如：开发时期采用的某个版本，但是升级后的版本可能有大的变动，比如删除了你使用的某个 api，或者某个方法调用方式变了等各种不确定的变动，自动升级有风险

这个不会，因为用到是 semver 版本规范，会锁一个大版本更新，这个只会更新 小版本，例如 bug fix 等等

**Comment by Hongbusi** [comment]
可以试试，刚好可以学习一下，遇到问题在修复就好了。

**Comment by whylost** [comment]
@Hongbusi 
https://github.com/marketplace/renovate

**Comment by Hongbusi** [comment]
@alexzhang1030
