### ISSUE TITLE
全局图片懒加载指令及图片展示错误处理

### ISSUE THREAD

**Issue by jersonwei** [developer-plus/vue-hbs-admin#34]
### Clear and concise description of the problem

图片懒加载:优化页面的性能,减少不必要的DOM渲染,自定义指令可全局使用

**Comment by Hongbusi** [comment]
- 全局图片懒加载指令及图片展示错误处理
- 组件数据懒加载

看起来像是两个需求。（建议进行拆分，这样可以更好的管理 changelog）
另外，组件数据懒加载可以描述的再详细一些。

**Comment by jersonwei** [comment]
> * 全局图片懒加载指令及图片展示错误处理
> * 组件数据懒加载
> 
> 看起来像是两个需求。（建议进行拆分，这样可以更好的管理 changelog） 另外，组件数据懒加载可以描述的再详细一些。

因为逻辑都是相似的,都是在进入可视区域后执行相应的逻辑主要是只写个指令功能点不够====
