### ISSUE TITLE
全局异步任务进度展示器

### ISSUE THREAD

**Issue by Btrya** [developer-plus/vue-hbs-admin#40]
### 全局异步任务进度展示器

- 支持任意页面查看当前 如上传文件，报表导入/导出 等一系列异步任务的全局异步任务进度展示器
- 支持取消当个异步任务队列
- 支持配置新的异步任务
- 支持异步任务失败提醒
- 待补充...

**Comment by Hongbusi** [comment]
听起来挺有趣的。

这个要存在相当大数据的情况下才会使用的场景？有没有相关案例可以参考？
