### ISSUE TITLE
当水印被非预期操作移除时，重新绘制水印

### ISSUE THREAD

**Issue by ch3cknull** [developer-plus/vue-hbs-admin#64]
### 清晰简洁的问题描述

在 `useWaterMark` 中添加一个 `MutationObserver` 监听添加水印的节点 

当水印被非预期操作（用户操作等情况）移除时，重新绘制水印到对应节点

**Comment by RainyNight9** [comment]
这个 MutationObserver 我之前尝试过，页面会很卡，后结合非开发人员使用的话，应该没啥问题，后来就放弃了（毕竟很难防小人）。如果有人可以有想法也可以加一下试试效果，可能我之前使用姿势不对。
