### ISSUE TITLE
页面跳转时的样式过渡

### ISSUE THREAD

**Issue by MEIYA-yl** [developer-plus/vue-hbs-admin#83]
### Clear and concise description of the problem

路由跳转时 页面可以有一些渐出渐入的效果

**Comment by alexzhang1030** [comment]
现在就有啊

**Comment by MEIYA-yl** [comment]
可能是我没看出来，我建议是可以看到两个页面在过渡时（交替时，同时存在但透明度降低）的一个淡出一个淡入的效果。

**Comment by MEIYA-yl** [comment]
嗯 一开始是注意到了这个效果 ，然后也是遇见过上边我提到的那种过渡方式，感觉会更亮眼一些。

**Comment by Hongbusi** [comment]
有 demo 可以发来看看

**Comment by MEIYA-yl** [comment]
找到后我再贴一下
